  CREATE TABLE "XX_FUSION_PICK_SLIP_DTLS_TEMP_TB" 
   (	"ID" NUMBER, 
	"PICK_SLIP_NUMBER" VARCHAR2(240 BYTE), 
	"BATCH_ID" VARCHAR2(30 BYTE), 
	"PICKING_BATCH_NAME" VARCHAR2(30 BYTE), 
	"ITEM_NUMBER" VARCHAR2(30 BYTE), 
	"REQUESTED_QUANTITY" NUMBER, 
	"CUSTOMER" VARCHAR2(240 BYTE), 
	"SHIP_TO_LOCATION" VARCHAR2(4000 BYTE)
   )