
create table XX_ITEM_MASTER_DTLS_TB
(
item_id                 varchar2(100),
warehouse               varchar2(5),
barcode                 varchar2(40),
description             varchar2(960),
country_of_origin       varchar2(240),
item_code               varchar2(240),
color_code              varchar2(240),
type                    varchar2(240),
business_group_code     varchar2(240),
division_group_code     varchar2(240),
retail_group_code       varchar2(240),
local_description       varchar2(4000),
unique_description      varchar2(4000),
uom                     varchar2(25),
width                   varchar2(30),
gross_weight            varchar2(30),
net_weight              varchar2(30),
uom_weight              varchar2(30),
volume                  varchar2(30),
brand                   varchar2(80),
oracle_code             varchar2(300),
attribute1              varchar2(240),
attribute2              varchar2(240),
attribute3              varchar2(240),
attribute4              varchar2(240),
attribute5              varchar2(240),
attribute6              varchar2(240),
attribute7              varchar2(240),
attribute8              varchar2(240),
attribute9              varchar2(240),
attribute10             varchar2(240),
attribute11             varchar2(240),
attribute12             varchar2(240),
attribute13             varchar2(240),
attribute14             varchar2(240),
attribute15             varchar2(240),
creation_date           date, 
last_update_date        date, 
import_method           varchar2(100 byte), 
status                  varchar2(240 byte), 
request_payload         clob,
response_object         clob,
transaction_id          varchar2(4000),
result                  varchar2(4000),
messagetype             varchar2(4000),
messagecode             varchar2(4000),
message                 varchar2(4000),
success                 varchar2(30)
);

